version: '3.5'

services:
  front-end:
    image: example-frontend
    ports: 
      - 3000:3000
    container_name: frontend
    environment:
      - API_URL=http://localhost
    depends_on: 
      - backend
  backend:
    image: example-backend
    ports: 
      - 8080:8080
    container_name: backend
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
    container_name: redis
  postgres: 
    image: postgres:13.2-alpine
    ports:
      - 5000:8000
    restart: unless-stopped
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx: 
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: unless-stopped


