version: '3.5'

services:
  front-end:
    image: example-frontend
    ports: 
      - 3000:3000
  backend:
    image: example-backend
    ports: 
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
    container_name: redis
  postgres: 
    image: postgres:13.2-alpine
    ports:
      - 5000:5000
    restart: unless-stopped
    container_name: postgres
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
